from collections.abc import Callable
from collections.abc import Sequence as AbstractSequence
from typing import Any, cast

from sqlalchemy.engine import default
from sqlalchemy.engine.interfaces import DBAPICursor
from sqlalchemy.sql import compiler
from sqlalchemy.sql.schema import Sequence
from sqlalchemy.sql.type_api import TypeEngine

RESERVED_WORDS = frozenset(
    {
        "add",
        "admin",
        "after",
        "aggregate",
        "all",
        "alter",
        "always",
        "analyze",
        "and",
        "any",
        "asc",
        "asymmetric",
        "at",
        "atomic",
        "authorization",
        "auto_increment",
        "before",
        "begin",
        "best",
        "between",
        "big",
        "bigint",
        "bigserial",
        "binary",
        "blob",
        "by",
        "cache",
        "call",
        "cascade",
        "case",
        "cast",
        "century",
        "chain",
        "char",
        "character",
        "check",
        "client",
        "clob",
        "coalesce",
        "column",
        "comment",
        "commit",
        "committed",
        "constraint",
        "continue",
        "convert",
        "copy",
        "corresponding",
        "create",
        "cross",
        "cube",
        "current",
        "current_date",
        "current_role",
        "current_schema",
        "current_time",
        "current_timestamp",
        "current_timezone",
        "current_user",
        "cycle",
        "data",
        "date",
        "day",
        "deallocate",
        "debug",
        "dec",
        "decade",
        "decimal",
        "declare",
        "default",
        "delete",
        "delimiters",
        "desc",
        "diagnostics",
        "distinct",
        "do",
        "double",
        "dow",
        "doy",
        "drop",
        "each",
        "effort",
        "else",
        "elseif",
        "encrypted",
        "end",
        "endian",
        "epoch",
        "escape",
        "every",
        "except",
        "exclude",
        "exec",
        "execute",
        "exists",
        "explain",
        "external",
        "extract",
        "false",
        "first",
        "float",
        "following",
        "for",
        "foreign",
        "from",
        "full",
        "function",
        "fwf",
        "generated",
        "global",
        "grant",
        "group",
        "grouping",
        "groups",
        "having",
        "hour",
        "hugeint",
        "identity",
        "if",
        "ilike",
        "imprints",
        "in",
        "increment",
        "index",
        "inner",
        "insert",
        "int",
        "integer",
        "intersect",
        "interval",
        "into",
        "is",
        "isolation",
        "join",
        "key",
        "language",
        "large",
        "last",
        "lateral",
        "left",
        "level",
        "like",
        "limit",
        "little",
        "loader",
        "local",
        "localtime",
        "localtimestamp",
        "match",
        "matched",
        "maxvalue",
        "mediumint",
        "merge",
        "minute",
        "minvalue",
        "month",
        "name",
        "native",
        "natural",
        "new",
        "next",
        "no",
        "not",
        "now",
        "null",
        "nullif",
        "nulls",
        "numeric",
        "object",
        "of",
        "offset",
        "old",
        "on",
        "only",
        "option",
        "options",
        "or",
        "order",
        "ordered",
        "others",
        "outer",
        "over",
        "partial",
        "partition",
        "password",
        "path",
        "position",
        "preceding",
        "precision",
        "prep",
        "prepare",
        "preserve",
        "primary",
        "privileges",
        "procedure",
        "public",
        "quarter",
        "range",
        "read",
        "real",
        "records",
        "references",
        "referencing",
        "release",
        "remote",
        "rename",
        "repeatable",
        "replace",
        "replica",
        "restart",
        "restrict",
        "return",
        "returns",
        "revoke",
        "right",
        "role",
        "rollback",
        "rollup",
        "row",
        "rows",
        "sample",
        "savepoint",
        "schema",
        "second",
        "seed",
        "select",
        "sequence",
        "serial",
        "serializable",
        "server",
        "session",
        "session_user",
        "set",
        "sets",
        "simple",
        "size",
        "smallint",
        "some",
        "split_part",
        "start",
        "statement",
        "stdin",
        "stdout",
        "storage",
        "string",
        "substring",
        "symmetric",
        "table",
        "temp",
        "temporary",
        "text",
        "then",
        "ties",
        "time",
        "timestamp",
        "tinyint",
        "to",
        "trace",
        "transaction",
        "trigger",
        "true",
        "truncate",
        "type",
        "unbounded",
        "uncommitted",
        "unencrypted",
        "union",
        "unique",
        "update",
        "user",
        "using",
        "value",
        "values",
        "varchar",
        "varying",
        "view",
        "week",
        "when",
        "where",
        "while",
        "window",
        "with",
        "work",
        "write",
        "xmlagg",
        "xmlattributes",
        "xmlcomment",
        "xmlconcat",
        "xmldocument",
        "xmlelement",
        "xmlforest",
        "xmlnamespaces",
        "xmlparse",
        "xmlpi",
        "xmlquery",
        "xmlschema",
        "xmltext",
        "xmlvalidate",
        "year",
        "zone",
    }
)


class MonetDBIdentifierPreparer(compiler.IdentifierPreparer):
    reserved_words = RESERVED_WORDS
    illegal_initial_characters = {str(digit) for digit in range(10)} | {"_", "$"}


class MonetDBCursor:
    """DB-API cursor wrapper that reports "no result set" as ``None``.

    DRIVER-WORKAROUND(adbc-driver-manager #3, upstream): not fixed by an
    adbc-driver-monetdb release; keep until Apache arrow-adbc changes it.

    ADBC always hands back an Arrow stream, so ``adbc_driver_manager`` derives
    an empty ``description`` list for DDL and for DML without RETURNING. PEP 249
    requires ``None`` there, and SQLAlchemy relies on that to decide whether a
    statement returned rows: an empty list is falsy but not ``None``, so it
    would build a zero-column result instead of a no-rows result.
    """

    __slots__ = (
        "_cursor",
        "close",
        "execute",
        "executemany",
        "fetchall",
        "fetchmany",
        "fetchone",
    )

    def __init__(self, cursor: Any) -> None:
        self._cursor = cursor
        self.execute: Callable[..., Any] = cursor.execute
        self.executemany: Callable[..., Any] = cursor.executemany
        self.fetchone: Callable[[], Any] = cursor.fetchone
        self.fetchmany: Callable[..., Any] = cursor.fetchmany
        self.fetchall: Callable[[], Any] = cursor.fetchall
        self.close: Callable[[], None] = cursor.close

    @property
    def description(self) -> AbstractSequence[Any] | None:
        return self._cursor.description or None

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def adbc_cursor(self) -> Any:
        return self._cursor

    def __getattr__(self, name: str) -> Any:
        return getattr(self._cursor, name)


class MonetDBExecutionContext(default.DefaultExecutionContext):
    def create_cursor(self) -> DBAPICursor:
        return cast(DBAPICursor, MonetDBCursor(self._dbapi_connection.cursor()))

    def fire_sequence(self, seq: Sequence, type_: TypeEngine[Any]) -> int:
        name = self.identifier_preparer.format_sequence(seq)
        return self._execute_scalar(f"SELECT NEXT VALUE FOR {name}", type_)
