import re

AUTOINCREMENT_DEFAULT = re.compile(r'^next value for "(?P<schema>[^"]+)"\."(?P<sequence>[^"]+)"$')

TABLE_TYPE_TABLE = 0
TABLE_TYPE_VIEW = 1
TABLE_TYPE_MERGE = 3
TABLE_TYPE_REMOTE = 5
TABLE_TYPE_REPLICA = 6
TABLE_TYPE_LOCAL_TEMPORARY = 30

TABLE_TYPES = (TABLE_TYPE_TABLE, TABLE_TYPE_MERGE, TABLE_TYPE_REMOTE, TABLE_TYPE_REPLICA)

KEY_TYPE_PRIMARY = 0
KEY_TYPE_UNIQUE = 1
KEY_TYPE_FOREIGN = 2
KEY_TYPE_CHECK = 4

FK_ACTIONS = {
    0: "NO ACTION",
    1: "CASCADE",
    2: "RESTRICT",
    3: "SET NULL",
    4: "SET DEFAULT",
}
